import Head from "next/head";
import FilterDropdown from "@/components/FilterDropdown";
import { FilterSetting } from "@/utils/products";
import { getAllFilterSettings } from "@/utils/products";

export async function getServerSideProps(context: any) {
  const settings = await getAllFilterSettings();
  return {
    props: {
      filterSettings: settings,
    },
  };
}

interface Props {
  filterSettings: FilterSetting[];
}

export default function Catalog({ filterSettings }: Props) {
  return (
    <>
      <Head>
        <title>Sota | Каталог</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ minHeight: "100vh", display: "grid", placeContent: "center" }}
      >
        <div style={{ display: "flex" }}>
          {filterSettings.map((setting) => (
            <FilterDropdown
              key={setting.name}
              {...setting}
              handleChangeFilterSetting={() => {}}
            />
          ))}
        </div>
      </main>
    </>
  );
}
