import Head from "next/head";

export default function Catalog() {
  return (
    <>
      <Head>
        <title>Sota | Каталог</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ minHeight: "100vh", display: "grid", placeContent: "center" }}
      >
        <h1>This is catalog</h1>
      </main>
    </>
  );
}
